def lint()
    use_frameworks!
    pod 'SwiftLint'
end

def pods()
  use_frameworks!
  pod 'DynamicKit/Core', :path => "../"
  pod 'DynamicKit/Eval', :path => "../"
  pod 'DynamicKit/UIKit', :path => "../"
  pod 'DynamicKit/Runtime', :path => "../"
  lint()
end

target 'Sample' do
  platform :ios, '9.0'
  pods()
end
